services:
  back-end:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL:
      DB_USER:
      DB_PASSWORD:
  front-end:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - back-end
